llna = int(input("Wat is het aantal leerlingen in klas A? "))
llnb = int(input("Wat is het aantal leerlingen in klas B? ")) 
llnc = int(input("Wat is het aantal leerlingen in klas C? ")) 
eerste = (llna%2)
tweede = ((llna+eerste)//2)
derde = (llnb%2)
vierde = ((llnb+derde)//2)
vijfde = (llnc%2)
zesde = ((llnc+vijfde)//2)
totaal = (tweede+vierde+zesde)
print(totaal)
